version: '3'

services:
  odoo:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: odoo
    ports:
      - "8069:8069"
    volumes:
      - ./app:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=mydb
    command: ["odoo-bin", "-r", "dbuser", "-w", "dbpassword", "--addons-path=/app/addons", "-d", "mydb"]
    depends_on:
      - postgres
    networks:
      - odoo_net

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - odoo_net

networks:
  odoo_net:
